import { Brand } from "@/components/Brand";
import PublicBottomNav from "@/components/PublicBottomNav";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { localLoginPath } from "@/lib/localAuth";
import { trpc } from "@/lib/trpc";
import { Camera, Heart, ImagePlus, Loader2, MapPin, MessageCircle, Send, ShieldCheck, X } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

function readFileAsBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Não foi possível ler a foto.")); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(file); }); }
function formatDate(value: Date | string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(value)); }

function MuralCard({ post, canInteract }: { post: any; canInteract: () => boolean }) {
  const utils = trpc.useUtils();
  const [, setLocation] = useLocation();
  const like = trpc.mural.toggleLike.useMutation({ onSuccess: () => utils.mural.feed.invalidate() });
  const toggleLike = () => { if (!canInteract()) return setLocation(localLoginPath("/mural")); like.mutate({ muralPostId: post.id }); };
  return <article className="overflow-hidden rounded-[1.6rem] bg-white shadow-sm ring-1 ring-[#0b6976]/8"><div className="flex items-center justify-between gap-3 p-5"><div><p className="font-bold text-[#164e57]">{post.authorName || "Morador do Sal"}</p><p className="mt-1 text-xs text-[#68888d]">{formatDate(post.createdAt)}{post.locationLabel ? ` · ${post.locationLabel}` : ""}</p></div><span className="grid h-9 w-9 place-items-center rounded-full bg-[#edf7f5] text-[#0b8793]"><MapPin className="h-4 w-4" /></span></div>{post.images[0] && <Link href={`/mural/${post.id}`}><div className="grid grid-cols-2 gap-1 bg-[#edf7f5]">{post.images.slice(0, 4).map((image: any, index: number) => <img key={image.id} src={image.imageUrl} alt="Foto publicada no Mural do Sal" className={`h-48 w-full object-cover ${post.images.length === 1 ? "col-span-2 h-80" : ""} ${index > 1 ? "hidden sm:block" : ""}`} />)}</div></Link>}<div className="p-5"><p className="whitespace-pre-line text-sm leading-6 text-[#315d64]">{post.caption}</p><div className="mt-5 flex items-center gap-2 border-t border-[#e5efed] pt-4"><Button variant="ghost" size="sm" onClick={toggleLike} disabled={like.isPending} className={`rounded-full ${post.likedByViewer ? "text-[#d95e68]" : "text-[#55777d]"}`}><Heart className={`h-4 w-4 ${post.likedByViewer ? "fill-current" : ""}`} />{post.likeCount}</Button>{post.allowsComments ? <Link href={`/mural/${post.id}`} className="inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm font-bold text-[#55777d] hover:bg-[#edf7f5]"><MessageCircle className="h-4 w-4" />Comentar</Link> : <span className="px-3 text-xs font-bold text-[#8a989a]">Comentários desativados</span>}</div></div></article>;
}

export default function Mural() {
  const [, setLocation] = useLocation();
  const { data: user } = trpc.auth.me.useQuery();
  const { data: posts = [], isLoading } = trpc.mural.feed.useQuery();
  const [composerOpen, setComposerOpen] = useState(false);
  const canInteract = () => Boolean(user);
  return <main className="min-h-screen bg-[#f7f3ea] pb-28 text-[#063b43] sm:pb-32"><header className="bg-[#073c45] pb-16 pt-6 text-white"><div className="container flex items-center justify-between gap-4"><Link href="/" className="rounded-full bg-white/10 px-3 py-2"><Brand className="[&_p:first-child]:text-white [&_p:last-child]:text-[#a8d9d8] [&>div]:hidden sm:[&>div]:block" /></Link><Button onClick={() => user ? setComposerOpen(true) : setLocation(localLoginPath("/mural"))} className="rounded-full bg-[#f4cf7c] text-[#073c45] hover:bg-[#ffe3a0]"><ImagePlus className="h-4 w-4" />Publicar</Button></div><div className="container mt-11"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f4cf7c]">Mural do Sal</p><h1 className="mt-3 max-w-2xl font-display text-5xl leading-[0.96] tracking-[-0.06em] sm:text-6xl">O Sal pelos olhos de quem vive aqui.</h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#c5e0dc] sm:text-base">Compartilhe seus momentos, praias, paisagens e descobertas. Todo conteúdo é aprovado antes de aparecer para a comunidade.</p></div></header><section className="container -mt-7"><div className="rounded-[1.7rem] bg-[#edf8f6] p-5 shadow-[0_18px_35px_rgba(6,59,67,0.08)]"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#0b8793]" /><p className="text-sm leading-6 text-[#38666d]">Cada publicação é analisada pelo administrador. Você decide se as pessoas poderão ou não comentar sua foto.</p></div></div>{isLoading ? <div className="grid min-h-80 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#0b8793]" /></div> : posts.length ? <div className="mt-7 grid gap-5 lg:grid-cols-2">{posts.map(post => <MuralCard key={post.id} post={post} canInteract={canInteract} />)}</div> : <div className="mt-7 grid min-h-80 place-items-center rounded-[1.8rem] border border-dashed border-[#9ccdc8] bg-white p-8 text-center"><div><Camera className="mx-auto h-9 w-9 text-[#0b8793]" /><h2 className="mt-4 font-display text-3xl">O Mural está esperando o primeiro olhar.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#5a7d82]">Publique uma foto real de Salinas e ela aparecerá aqui após aprovação.</p><Button onClick={() => user ? setComposerOpen(true) : setLocation(localLoginPath("/mural"))} className="mt-5 rounded-full bg-[#073c45] text-white">Criar publicação</Button></div></div>}</section>{composerOpen && <MuralComposer onClose={() => setComposerOpen(false)} />}<PublicBottomNav /></main>;
}

function MuralComposer({ onClose }: { onClose: () => void }) {
  const utils = trpc.useUtils();
  const upload = trpc.mural.uploadImage.useMutation();
  const create = trpc.mural.create.useMutation({ onSuccess: () => { utils.mural.feed.invalidate(); toast.success("Publicação enviada para aprovação."); onClose(); } });
  const [caption, setCaption] = useState(""); const [images, setImages] = useState<string[]>([]); const [allowsComments, setAllowsComments] = useState(true); const [locationLabel, setLocationLabel] = useState(""); const [coords, setCoords] = useState<{ latitude: number; longitude: number } | null>(null);
  const uploadFiles = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []).slice(0, 4 - images.length); try { const urls = await Promise.all(files.map(async file => { if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) throw new Error("Use JPEG, PNG ou WebP de até 5 MB."); return (await upload.mutateAsync({ fileName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp", base64: await readFileAsBase64(file) })).url; })); setImages(current => [...current, ...urls]); } catch (error) { toast.error(error instanceof Error ? error.message : "Falha ao enviar fotos."); } finally { event.target.value = ""; } };
  const useLocation = () => { if (!navigator.geolocation) return toast.error("Seu navegador não oferece geolocalização."); navigator.geolocation.getCurrentPosition(value => { setCoords({ latitude: value.coords.latitude, longitude: value.coords.longitude }); toast.success("Localização adicionada."); }, () => toast.error("Não foi possível usar sua localização."), { enableHighAccuracy: true, timeout: 10000 }); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!images.length) return toast.error("Envie pelo menos uma foto."); create.mutate({ caption, images, allowsComments, locationLabel: locationLabel || null, latitude: coords?.latitude ?? null, longitude: coords?.longitude ?? null }); };
  return <div className="fixed inset-0 z-[70] overflow-y-auto bg-[#063b43]/50 p-4 backdrop-blur-sm"><form onSubmit={submit} className="mx-auto my-8 max-w-xl rounded-[1.8rem] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#d68d20]">Mural do Sal</p><h2 className="mt-1 font-display text-3xl text-[#063b43]">Compartilhe seu momento</h2></div><Button type="button" variant="ghost" size="icon" onClick={onClose} className="rounded-full"><X className="h-5 w-5" /></Button></div><div className="mt-5"><Label>Legenda</Label><Textarea value={caption} onChange={event => setCaption(event.target.value)} required maxLength={2200} className="mt-2 min-h-28" placeholder="O que está acontecendo em Salinas?" /></div><div className="mt-5 flex items-center justify-between"><div><Label>Fotos</Label><p className="mt-1 text-xs text-[#6a898d]">Até quatro fotos.</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-full bg-[#edf7f5] px-4 py-2 text-sm font-bold text-[#0b7e8a]"><ImagePlus className="h-4 w-4" />Adicionar<input type="file" className="hidden" accept="image/jpeg,image/png,image/webp" multiple onChange={uploadFiles} /></label></div>{images.length ? <div className="mt-3 grid grid-cols-4 gap-2">{images.map(image => <img key={image} src={image} alt="Prévia" className="aspect-square rounded-xl object-cover" />)}</div> : null}<div className="mt-5 grid gap-4 rounded-2xl bg-[#edf8f6] p-4"><label className="flex items-center justify-between gap-4 text-sm font-bold text-[#285961]"><span>Permitir comentários nesta publicação</span><input type="checkbox" checked={allowsComments} onChange={event => setAllowsComments(event.target.checked)} className="h-4 w-4 accent-[#0a7c87]" /></label><div><Label>Local (opcional)</Label><Input value={locationLabel} onChange={event => setLocationLabel(event.target.value)} className="mt-2 bg-white" placeholder="Ex.: Praia do Atalaia" /></div><Button type="button" variant="outline" onClick={useLocation} className="w-fit rounded-full border-[#0b7e8a]/25 text-[#0b7e8a]"><MapPin className="h-4 w-4" />{coords ? "Geolocalização adicionada" : "Usar minha geolocalização"}</Button></div><Button type="submit" disabled={create.isPending || upload.isPending} className="mt-6 rounded-full bg-[#073c45] text-white">{create.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}Enviar para aprovação</Button></form></div>;
}

export function MuralDetail({ id }: { id: number }) {
  const [, setLocation] = useLocation();
  const { data: user } = trpc.auth.me.useQuery(); const { data: post, isLoading } = trpc.mural.detail.useQuery({ id }); const utils = trpc.useUtils();
  const comment = trpc.mural.comment.useMutation({ onSuccess: () => { utils.mural.detail.invalidate({ id }); toast.success("Comentário enviado para aprovação."); } }); const [body, setBody] = useState("");
  if (isLoading || !post) return <div className="grid min-h-screen place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#0b8793]" /></div>;
  const submit = (event: FormEvent) => { event.preventDefault(); if (!user) return setLocation(localLoginPath(`/mural/${id}`)); comment.mutate({ muralPostId: id, body }); setBody(""); };
  return <main className="min-h-screen bg-[#f7f3ea] pb-24"><div className="container max-w-3xl py-8"><Link href="/mural" className="text-sm font-bold text-[#0b7e8a]">← Mural do Sal</Link><article className="mt-5 overflow-hidden rounded-[1.8rem] bg-white shadow-sm">{post.images[0] && <img src={post.images[0].imageUrl} alt="Publicação do Mural" className="max-h-[34rem] w-full object-cover" />}<div className="p-6"><p className="font-bold text-[#164e57]">{post.authorName || "Morador do Sal"}</p><p className="mt-1 text-xs text-[#68888d]">{formatDate(post.createdAt)}{post.locationLabel ? ` · ${post.locationLabel}` : ""}</p><p className="mt-5 whitespace-pre-line text-sm leading-7 text-[#315d64]">{post.caption}</p></div></article><section className="mt-5 rounded-[1.8rem] bg-white p-6 shadow-sm"><h2 className="font-display text-2xl text-[#063b43]">Comentários</h2>{post.allowsComments ? <form onSubmit={submit} className="mt-4 flex gap-2"><Input value={body} onChange={event => setBody(event.target.value)} required placeholder="Escreva um comentário" /><Button type="submit" disabled={comment.isPending} className="rounded-full bg-[#073c45] text-white"><Send className="h-4 w-4" /></Button></form> : <p className="mt-3 text-sm text-[#6a898d]">O autor desativou os comentários nesta publicação.</p>}<div className="mt-5 grid gap-3">{post.comments.map((item: any) => <div key={item.id} className="rounded-2xl bg-[#edf8f6] p-4"><p className="text-sm font-bold text-[#164e57]">{item.authorName || "Usuário"}</p><p className="mt-1 text-sm text-[#426b71]">{item.body}</p></div>)}{!post.comments.length && <p className="text-sm text-[#6a898d]">Nenhum comentário aprovado ainda.</p>}</div></section></div><PublicBottomNav /></main>;
}
