import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Loader2, MessageCircle, ShieldCheck, XCircle } from "lucide-react";
import { toast } from "sonner";

export default function AdminMuralPanel() {
  const utils = trpc.useUtils(); const { data, isLoading } = trpc.admin.muralModeration.useQuery(); const refresh = () => utils.admin.muralModeration.invalidate();
  const reviewPost = trpc.admin.reviewMuralPost.useMutation({ onSuccess: () => { refresh(); toast.success("Publicação revisada."); } }); const reviewComment = trpc.admin.reviewMuralComment.useMutation({ onSuccess: () => { refresh(); toast.success("Comentário revisado."); } });
  if (isLoading || !data) return <div className="grid min-h-56 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#0b8793]" /></div>;
  return <section className="grid gap-6"><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-[#0b6976]/8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf7f5] text-[#0b7e8a]"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-display text-2xl text-[#063b43]">Publicações aguardando aprovação</h2><p className="text-sm text-[#648187]">Revise fotos, legenda e localização antes de exibir no Mural.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2">{data.posts.map(post => <article key={post.id} className="overflow-hidden rounded-2xl border border-[#e0efec]">{post.images[0] && <img src={post.images[0].imageUrl} alt="Prévia da publicação" className="h-44 w-full object-cover" />}<div className="p-4"><p className="font-bold text-[#164e57]">{post.authorName || "Usuário"}</p><p className="mt-2 text-sm leading-6 text-[#426b71]">{post.caption}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => reviewPost.mutate({ id: post.id, approved: true })} className="rounded-full bg-[#0e916e] text-white"><CheckCircle2 className="h-4 w-4" />Aprovar</Button><Button size="sm" variant="outline" onClick={() => reviewPost.mutate({ id: post.id, approved: false })} className="rounded-full text-destructive"><XCircle className="h-4 w-4" />Recusar</Button></div></div></article>)}{!data.posts.length && <p className="rounded-2xl bg-[#edf7f5] p-5 text-sm text-[#5b7d82]">Não há publicações pendentes.</p>}</div></div><div className="rounded-[1.5rem] bg-white p-5 shadow-sm ring-1 ring-[#0b6976]/8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf7f5] text-[#0b7e8a]"><MessageCircle className="h-5 w-5" /></span><div><h2 className="font-display text-2xl text-[#063b43]">Comentários aguardando aprovação</h2><p className="text-sm text-[#648187]">Comentários só são exibidos após sua revisão.</p></div></div><div className="mt-5 grid gap-3">{data.comments.map(comment => <article key={comment.id} className="flex flex-col justify-between gap-3 rounded-2xl border border-[#e0efec] p-4 sm:flex-row sm:items-center"><div><p className="font-bold text-[#164e57]">{comment.authorName || "Usuário"}</p><p className="mt-1 text-sm text-[#426b71]">{comment.body}</p><p className="mt-2 text-xs text-[#6a898d]">Em: {comment.postCaption}</p></div><div className="flex gap-2"><Button size="sm" onClick={() => reviewComment.mutate({ id: comment.id, approved: true })} className="rounded-full bg-[#0e916e] text-white">Aprovar</Button><Button size="sm" variant="outline" onClick={() => reviewComment.mutate({ id: comment.id, approved: false })} className="rounded-full text-destructive">Recusar</Button></div></article>)}{!data.comments.length && <p className="rounded-2xl bg-[#edf7f5] p-5 text-sm text-[#5b7d82]">Não há comentários pendentes.</p>}</div></div></section>;
}
